---
- hosts: localhost
  tasks:
    - import_tasks: lib/packages/init.yml
    - import_tasks: lib/flatpak/init.yml
    - import_tasks: lib/apps/init.yml
    - import_tasks: lib/zsh/init.yml
    - import_tasks: lib/configs/init.yml
    
    - import_tasks: lib/customrc.yml
    - import_tasks: lib/git.yml
    - import_tasks: lib/fonts.yml

    - import_tasks: lib/scripts.yml
    - import_tasks: lib/reload-wallpaper.yml

    - import_tasks: lib/end-message.yml